trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - main

variables:
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: backendProjectPath
    value: 'ReleaseFlow.WebApp/ReleaseFlow.WebApp.csproj'

stages:
  - stage: 'Build_Test'
    jobs:
      - job: "Build"
        displayName: 'Build and Test'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: azure-pipelines-template.yml
